#!/bin/python

import math
import os
import random
import re
import sys


# Complete the hackerlandRadioTransmitters function below.
def hackerlandRadioTransmitters(x, k):
    x.sort()
    count = 0
    index = 0
    begin = False
    middle = False

    while index < len(x):
        if begin == False:
            number = x[index] + k
            begin = True
            index += 1
            count += 1
        elif middle == False and number >= x[index]:
            middle = True
            while index < len(x) and number >= x[index]:
                index += 1
            number = x[index - 1] + k
        elif middle == False and number < x[index]:
            begin = False
        else:
            while index < len(x) and number >= x[index]:
                index += 1
            begin = False
            middle = False

    return count


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')
    nk = raw_input().split()
    n = int(nk[0])
    k = int(nk[1])
    x = map(int, raw_input().rstrip().split())
    result = hackerlandRadioTransmitters(x, k)
    fptr.write(str(result) + '\n')
    fptr.close()
